name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name : Set up build environment
      run: sudo apt install -y libssl-dev libxxhash-dev
      working-directory: build

    - name: Check base build
      run: make all
      working-directory: build

    - name: Check SIMD build
      run: make simd_all
      working-directory: build

